// $Id$
package jp.co.daifuku.wms.stock.display.deadstockinquiry;

/*
 * Copyright(c) 2000-2010 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
import java.io.File;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import jp.co.daifuku.Constants;
import jp.co.daifuku.authentication.DfkUserInfo;
import jp.co.daifuku.bluedog.model.PagerModel;
import jp.co.daifuku.bluedog.model.table.AreaCellColumn;
import jp.co.daifuku.bluedog.model.table.DateCellColumn;
import jp.co.daifuku.bluedog.model.table.ListCellKey;
import jp.co.daifuku.bluedog.model.table.ListCellLine;
import jp.co.daifuku.bluedog.model.table.ListCellModel;
import jp.co.daifuku.bluedog.model.table.LocationCellColumn;
import jp.co.daifuku.bluedog.model.table.NumberCellColumn;
import jp.co.daifuku.bluedog.model.table.StringCellColumn;
import jp.co.daifuku.bluedog.sql.ConnectionManager;
import jp.co.daifuku.bluedog.ui.control.Pager;
import jp.co.daifuku.bluedog.util.ControlColor;
import jp.co.daifuku.bluedog.util.Formatter;
import jp.co.daifuku.bluedog.webapp.ActionEvent;
import jp.co.daifuku.bluedog.webapp.DialogEvent;
import jp.co.daifuku.bluedog.webapp.DialogParameters;
import jp.co.daifuku.bluedog.webapp.ForwardParameters;
import jp.co.daifuku.bluedog.webapp.ViewState;
import jp.co.daifuku.common.CommonException;
import jp.co.daifuku.common.CommonParam;
import jp.co.daifuku.common.ExceptionHandler;
import jp.co.daifuku.common.text.StringUtil;
import jp.co.daifuku.emanager.EmConstants;
import jp.co.daifuku.emanager.util.P11LogWriter;
import jp.co.daifuku.foundation.common.ConvertUtil;
import jp.co.daifuku.foundation.common.DBUtil;
import jp.co.daifuku.foundation.common.DfkDateFormat.DATE_FORMAT;
import jp.co.daifuku.foundation.common.DfkDateFormat.TIME_FORMAT;
import jp.co.daifuku.foundation.common.Params;
import jp.co.daifuku.foundation.common.part11.Part11List;
import jp.co.daifuku.foundation.da.DataAccessSCH;
import jp.co.daifuku.foundation.da.Exporter;
import jp.co.daifuku.foundation.da.ExporterFactory;
import jp.co.daifuku.foundation.print.PrintExporter;
import jp.co.daifuku.ui.web.BusinessClassHelper;
import jp.co.daifuku.util.CollectionUtils;
import jp.co.daifuku.wms.base.controller.PulldownController.AreaType;
import jp.co.daifuku.wms.base.controller.PulldownController.StationType;
import jp.co.daifuku.wms.base.controller.PulldownController;
import jp.co.daifuku.wms.base.report.WmsExporterFactory;
import jp.co.daifuku.wms.base.util.SessionUtil;
import jp.co.daifuku.wms.stock.dasch.DeadStockInquiryDASCH;
import jp.co.daifuku.wms.stock.dasch.DeadStockInquiryDASCHParams;
import jp.co.daifuku.wms.stock.display.deadstockinquiry.DeadStockInquiry;
import jp.co.daifuku.wms.stock.exporter.DeadStockInqListParams;

/**
 * Most of the business logic in this class is generated by BusiTune
 *
 * @version $Revision$, $Date$
 * @author  BusiTune.
 * @author  Last commit: $Author$
 */
public class DeadStockInquiryBusiness
        extends DeadStockInquiry
{
    //------------------------------------------------------------
    // fields (upper case only)
    //------------------------------------------------------------
    /** key */
    private static final String _KEY_CONFIRMSOURCE = "_KEY_CONFIRMSOURCE";

    /** key */
    private static final String _KEY_DASCH = "_KEY_DASCH";

    /** key */
    private static final String _KEY_PAGERSOURCE = "_KEY_PAGERSOURCE";

    /** key */
    private static final String _KEY_POPUPSOURCE = "_KEY_POPUPSOURCE";

    /** lst_LongDwellList(LST_RETRIEVAL_DAY) */
    private static final ListCellKey KEY_LST_RETRIEVAL_DAY = new ListCellKey("LST_RETRIEVAL_DAY", new DateCellColumn(DATE_FORMAT.LONG, null), true, false);

    /** lst_LongDwellList(LST_ITEM_CODE) */
    private static final ListCellKey KEY_LST_ITEM_CODE = new ListCellKey("LST_ITEM_CODE", new StringCellColumn(), true, false);

    /** lst_LongDwellList(LST_ITEM_NAME) */
    private static final ListCellKey KEY_LST_ITEM_NAME = new ListCellKey("LST_ITEM_NAME", new StringCellColumn(), true, false);

    /** lst_LongDwellList(LST_LOT_NO) */
    private static final ListCellKey KEY_LST_LOT_NO = new ListCellKey("LST_LOT_NO", new StringCellColumn(), true, false);

    /** lst_LongDwellList(LST_AREA_NO) */
    private static final ListCellKey KEY_LST_AREA_NO = new ListCellKey("LST_AREA_NO", new AreaCellColumn(), true, false);

    /** lst_LongDwellList(LST_LOCATION_NO) */
    private static final ListCellKey KEY_LST_LOCATION_NO = new ListCellKey("LST_LOCATION_NO", new LocationCellColumn(), true, false);

    /** lst_LongDwellList(LST_ENTERING_QTY) */
    private static final ListCellKey KEY_LST_ENTERING_QTY = new ListCellKey("LST_ENTERING_QTY", new NumberCellColumn(0), true, false);

    /** lst_LongDwellList(LST_STOCK_CASE_QTY) */
    private static final ListCellKey KEY_LST_STOCK_CASE_QTY = new ListCellKey("LST_STOCK_CASE_QTY", new NumberCellColumn(0), true, false);

    /** lst_LongDwellList(LST_STOCK_PIECE_QTY) */
    private static final ListCellKey KEY_LST_STOCK_PIECE_QTY = new ListCellKey("LST_STOCK_PIECE_QTY", new NumberCellColumn(0), true, false);

    /** lst_LongDwellList(LST_JAN) */
    private static final ListCellKey KEY_LST_JAN = new ListCellKey("LST_JAN", new StringCellColumn(), true, false);

    /** lst_LongDwellList(LST_ITF) */
    private static final ListCellKey KEY_LST_ITF = new ListCellKey("LST_ITF", new StringCellColumn(), true, false);

    /** lst_LongDwellList keys */
    private static final ListCellKey[] LST_LONGDWELLLIST_KEYS = {
        KEY_LST_RETRIEVAL_DAY,
        KEY_LST_ITEM_CODE,
        KEY_LST_LOT_NO,
        KEY_LST_AREA_NO,
        KEY_LST_ENTERING_QTY,
        KEY_LST_STOCK_CASE_QTY,
        KEY_LST_JAN,
        KEY_LST_ITEM_NAME,
        KEY_LST_LOCATION_NO,
        KEY_LST_STOCK_PIECE_QTY,
        KEY_LST_ITF,
    };

    //------------------------------------------------------------
    // class variables (prefix '$')
    //------------------------------------------------------------

    //------------------------------------------------------------
    // instance variables (prefix '_')
    //------------------------------------------------------------
    /** PagerModel */
    private PagerModel _pager;

    /** ListCellModel lst_LongDwellList */
    private ListCellModel _lcm_lst_LongDwellList;

    //------------------------------------------------------------
    // constructors
    //------------------------------------------------------------
    /**
     * Default constructor
     */
    public DeadStockInquiryBusiness()
    {
        super();
    }

    //------------------------------------------------------------
    // public methods
    //------------------------------------------------------------
    /**
     *
     * @param e ActionEvent
     * @throws Exception
     */
    public void page_Load(ActionEvent e)
            throws Exception
    {
        setTitle();

        // save a popup event source.
        viewState.setString(_KEY_POPUPSOURCE, request.getParameter(_KEY_POPUPSOURCE));

        // initialize pulldown models.
        initializePulldownModels();
    }

    /**
     *
     * @param e ActionEvent
     * @throws Exception
     */
    public void page_Initialize(ActionEvent e)
            throws Exception
    {
        // initialize components.
        initializeComponents();

        // process call.
        page_Initialize_Process();
    }

    /**
     *
     * @param e ActionEvent
     * @throws Exception
     */
    public void page_ConfirmBack(ActionEvent e)
            throws Exception
    {
        // get event source.
        String eventSource = viewState.getString(_KEY_CONFIRMSOURCE);
        if (eventSource == null)
        {
            return;
        }

        // remove event source.
        viewState.remove(_KEY_CONFIRMSOURCE);

        // check result.
        boolean isExecute = new Boolean(String.valueOf(e.getEventArgs().get(0))).booleanValue();
        if (!isExecute)
        {
            return;
        }

        // choose process.
        if (eventSource.equals("btn_Print_Click_Process"))
        {
            // process call.
            btn_Print_Click_Process(false);
        }
    }

    /**
     *
     * @param e ActionEvent
     * @throws Exception
     */
    public void btn_Display_Click(ActionEvent e)
            throws Exception
    {
        // process call.
        btn_Display_Click_Process();
    }

    /**
     *
     * @param e ActionEvent
     * @throws Exception
     */
    public void btn_Print_Click(ActionEvent e)
            throws Exception
    {
        // process call.
        btn_Print_Click_Process(true);
    }

    /**
     *
     * @param e ActionEvent
     * @throws Exception
     */
    public void btn_Xls_Click(ActionEvent e)
            throws Exception
    {
        // process call.
        btn_Xls_Click_Process();
    }

    /**
     *
     * @param e ActionEvent
     * @throws Exception
     */
    public void btn_Clear_Click(ActionEvent e)
            throws Exception
    {
        // process call.
        btn_Clear_Click_Process();
    }

    /**
     *
     * @param e ActionEvent
     * @throws Exception
     */
    public void pgr_U_First(ActionEvent e)
            throws Exception
    {
        _pager.first();
        pager_SetPage();
    }

    /**
     *
     * @param e ActionEvent
     * @throws Exception
     */
    public void pgr_U_Prev(ActionEvent e)
            throws Exception
    {
        _pager.previous();
        pager_SetPage();
    }

    /**
     *
     * @param e ActionEvent
     * @throws Exception
     */
    public void pgr_U_Next(ActionEvent e)
            throws Exception
    {
        _pager.next();
        pager_SetPage();
    }

    /**
     *
     * @param e ActionEvent
     * @throws Exception
     */
    public void pgr_U_Last(ActionEvent e)
            throws Exception
    {
        _pager.last();
        pager_SetPage();
    }

    /**
     *
     * @param e ActionEvent
     * @throws Exception
     */
    public void pgr_D_First(ActionEvent e)
            throws Exception
    {
        _pager.first();
        pager_SetPage();
    }

    /**
     *
     * @param e ActionEvent
     * @throws Exception
     */
    public void pgr_D_Prev(ActionEvent e)
            throws Exception
    {
        _pager.previous();
        pager_SetPage();
    }

    /**
     *
     * @param e ActionEvent
     * @throws Exception
     */
    public void pgr_D_Next(ActionEvent e)
            throws Exception
    {
        _pager.next();
        pager_SetPage();
    }

    /**
     *
     * @param e ActionEvent
     * @throws Exception
     */
    public void pgr_D_Last(ActionEvent e)
            throws Exception
    {
        _pager.last();
        pager_SetPage();
    }

    /**
     * Menu button click event handling.
     *
     * @param e ActionEvent, event information
     * @throws Exception
     */
    public void btn_ToMenu_Click(ActionEvent e)
            throws Exception
    {
        // Delete Connection From Session
        SessionUtil.deleteSession(getSession());
        // Forward to Submenu screen
        forward(BusinessClassHelper.getSubMenuPath(viewState.getString(Constants.M_MENUID_KEY)));
    }

    //------------------------------------------------------------
    // accessor methods
    //------------------------------------------------------------

    //------------------------------------------------------------
    // package methods
    //------------------------------------------------------------

    //------------------------------------------------------------
    // protected methods
    //------------------------------------------------------------

    //------------------------------------------------------------
    // private methods
    //------------------------------------------------------------
    /**
     *
     * @throws Exception
     */
    private void initializeComponents()
            throws Exception
    {
        // get locale.
        Locale locale = httpRequest.getLocale();

        // initialize pager control.
        _pager = new PagerModel(new Pager[]{pgr_U, pgr_D}, locale);

        // initialize lst_LongDwellList.
        _lcm_lst_LongDwellList = new ListCellModel(lst_LongDwellList, LST_LONGDWELLLIST_KEYS, locale);
        _lcm_lst_LongDwellList.setToolTipVisible(KEY_LST_RETRIEVAL_DAY, true);
        _lcm_lst_LongDwellList.setToolTipVisible(KEY_LST_ITEM_CODE, true);
        _lcm_lst_LongDwellList.setToolTipVisible(KEY_LST_ITEM_NAME, true);
        _lcm_lst_LongDwellList.setToolTipVisible(KEY_LST_LOT_NO, true);
        _lcm_lst_LongDwellList.setToolTipVisible(KEY_LST_AREA_NO, true);
        _lcm_lst_LongDwellList.setToolTipVisible(KEY_LST_LOCATION_NO, true);
        _lcm_lst_LongDwellList.setToolTipVisible(KEY_LST_ENTERING_QTY, true);
        _lcm_lst_LongDwellList.setToolTipVisible(KEY_LST_STOCK_CASE_QTY, true);
        _lcm_lst_LongDwellList.setToolTipVisible(KEY_LST_STOCK_PIECE_QTY, true);
        _lcm_lst_LongDwellList.setToolTipVisible(KEY_LST_JAN, true);
        _lcm_lst_LongDwellList.setToolTipVisible(KEY_LST_ITF, true);
    }

    /**
     *
     * @throws Exception
     */
    private void initializePulldownModels()
            throws Exception
    {
    }

    /**
     *
     * @throws Exception
     */
    private void dispose()
            throws Exception
    {
        // dispose DASCH.
        disposeDasch();
    }

    /**
     *
     * @throws Exception
     */
    private void disposeDasch()
            throws Exception
    {
        // disposing DASCH.
        DataAccessSCH dasch = (DataAccessSCH)session.getAttribute(_KEY_DASCH);
        if (dasch != null)
        {
            session.removeAttribute(_KEY_DASCH);
            dasch.close();
            DBUtil.close(dasch.getConnection());
        }
    }

    /**
     *
     * @param line ListCellLine
     * @throws Exception
     */
    private void lst_LongDwellList_SetLineToolTip(ListCellLine line)
            throws Exception
    {
        // set ToolTip content.
        line.setToolTip(null, null);
        line.addToolTip("LBL-W0130", KEY_LST_ITEM_NAME);
    }

    /**
     *
     * @throws Exception
     */
    private void pager_SetPage()
            throws Exception
    {
        // get event source.
        String eventSource = viewState.getString(_KEY_PAGERSOURCE);
        if (eventSource == null)
        {
            return;
        }

        // choose process.
        if (eventSource.equals("btn_Display_Click_Process"))
        {
            // process call.
            btn_Display_Click_Process_SetList();
        }
    }

    /**
     *
     * @throws Exception
     */
    private void page_Initialize_Process()
            throws Exception
    {
        // set focus.
        setFocus(txt_LastRetrievalDate);
    }

    /**
     *
     * @throws Exception
     */
    private void btn_Display_Click_Process()
            throws Exception
    {
        // get locale.
        DfkUserInfo ui = (DfkUserInfo)getUserInfo();
        Locale locale = httpRequest.getLocale();

        Connection conn = null;
        DeadStockInquiryDASCH dasch = null;
        boolean isSuccess = false;
        try
        {
            // dispose DASCH.
            disposeDasch();

            // save a pager event source.
            viewState.setString(_KEY_PAGERSOURCE, "btn_Display_Click_Process");

            // open connection.
            conn = ConnectionManager.getSessionConnection(this);
            dasch = new DeadStockInquiryDASCH(conn, this.getClass(), locale, ui);
            dasch.setForwardOnly(false);

            // set input parameters.
            DeadStockInquiryDASCHParams inparam = new DeadStockInquiryDASCHParams();
            inparam.set(DeadStockInquiryDASCHParams.LAST_RETRIEVAL_DATE, txt_LastRetrievalDate.getValue());

            // get count.
            int count = dasch.count(inparam);
            _pager.clear();
            _pager.setMax(count);
            _lcm_lst_LongDwellList.clear();

            if (count == 0)
            {
                message.setMsgResourceKey("6003011");
                return;
            }
            else if (count > _pager.getMax())
            {
                message.setMsgResourceKey("6001023\t" + Formatter.getNumFormat(count)
                        + "\t" + Formatter.getNumFormat(_pager.getMax()));
            }
            else
            {
                message.setMsgResourceKey("6001022\t" + Formatter.getNumFormat(count));
            }

            // DASCH call.
            dasch.search(inparam);

            // save session.
            session.setAttribute(_KEY_DASCH, dasch);
            isSuccess = true;
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
            message.setMsgResourceKey(ExceptionHandler.getDisplayMessage(ex, this));
            _pager.clear();
            _lcm_lst_LongDwellList.clear();
        }
        finally
        {
            if (isSuccess)
            {
                // set list.
                btn_Display_Click_Process_SetList();
            }
            else
            {
                if (dasch != null)
                {
                    dasch.close();
                }
                DBUtil.close(conn);
            }
        }
    }

    /**
     *
     * @throws Exception
     */
    private void btn_Display_Click_Process_SetList()
            throws Exception
    {
        DeadStockInquiryDASCH dasch = null;
        try
        {
            // get session.
            dasch = (DeadStockInquiryDASCH)session.getAttribute(_KEY_DASCH);

            // output display.
            List<Params> outparams = dasch.get(_pager.getIndex() -1, _pager.getDataCountPerPage());
            _lcm_lst_LongDwellList.clear();
            for (Params outparam : outparams)
            {
                ListCellLine line = _lcm_lst_LongDwellList.getNewLine();
                line.setValue(KEY_LST_RETRIEVAL_DAY, outparam.get(DeadStockInquiryDASCHParams.RETRIEVAL_DAY));
                line.setValue(KEY_LST_ITEM_CODE, outparam.get(DeadStockInquiryDASCHParams.ITEM_CODE));
                line.setValue(KEY_LST_ITEM_NAME, outparam.get(DeadStockInquiryDASCHParams.ITEM_NAME));
                line.setValue(KEY_LST_LOT_NO, outparam.get(DeadStockInquiryDASCHParams.LOT_NO));
                line.setValue(KEY_LST_AREA_NO, outparam.get(DeadStockInquiryDASCHParams.AREA_NO));
                line.setValue(KEY_LST_LOCATION_NO, outparam.get(DeadStockInquiryDASCHParams.LOCATION_NO));
                line.setValue(KEY_LST_ENTERING_QTY, outparam.get(DeadStockInquiryDASCHParams.ENTERING_QTY));
                line.setValue(KEY_LST_STOCK_CASE_QTY, outparam.get(DeadStockInquiryDASCHParams.STOCK_CASE_QTY));
                line.setValue(KEY_LST_STOCK_PIECE_QTY, outparam.get(DeadStockInquiryDASCHParams.STOCK_PIECE_QTY));
                line.setValue(KEY_LST_JAN, outparam.get(DeadStockInquiryDASCHParams.JAN));
                line.setValue(KEY_LST_ITF, outparam.get(DeadStockInquiryDASCHParams.ITF));
                lst_LongDwellList_SetLineToolTip(line);
                _lcm_lst_LongDwellList.add(line);
            }
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
            message.setMsgResourceKey(ExceptionHandler.getDisplayMessage(ex, this));
            _pager.clear();
            _lcm_lst_LongDwellList.clear();
            disposeDasch();
        }
    }

    /**
     *
     * @param confirm
     * @throws Exception
     */
    private void btn_Print_Click_Process(boolean confirm)
            throws Exception
    {
        // input validation.
        txt_LastRetrievalDate.validate(this, true);

        // get locale.
        DfkUserInfo ui = (DfkUserInfo)getUserInfo();
        Locale locale = httpRequest.getLocale();

        Connection conn = null;
        DeadStockInquiryDASCH dasch = null;
        PrintExporter exporter = null;
        try
        {
            // open connection.
            conn = ConnectionManager.getRequestConnection(this);
            dasch = new DeadStockInquiryDASCH(conn, this.getClass(), locale, ui);
            dasch.setForwardOnly(true);

            // set input parameters.
            DeadStockInquiryDASCHParams inparam = new DeadStockInquiryDASCHParams();
            inparam.set(DeadStockInquiryDASCHParams.LAST_RETRIEVAL_DATE, txt_LastRetrievalDate.getValue());

            // check count.
            int count = dasch.count(inparam);
            if (confirm && count > 0)
            {
                // show confirm message.
                this.setConfirm("MSG-W0018\t" + Formatter.getNumFormat(count), false, true);
                viewState.setString(_KEY_CONFIRMSOURCE, "btn_Print_Click_Process");
                return;
            }
            else if (count == 0)
            {
                message.setMsgResourceKey("6003011");
                return;
            }

            // DASCH call.
            dasch.search(inparam);

            // open exporter.
            ExporterFactory factory = new WmsExporterFactory(locale, ui);
            exporter = factory.newPrinterExporter("DeadStockInqList", false);
            exporter.open();

            // export.
            while (dasch.next())
            {
                Params outparam = dasch.get();
                DeadStockInqListParams expparam = new DeadStockInqListParams();
                expparam.set(DeadStockInqListParams.DFK_DS_NO, outparam.get(DeadStockInquiryDASCHParams.DFK_DS_NO));
                expparam.set(DeadStockInqListParams.DFK_USER_ID, outparam.get(DeadStockInquiryDASCHParams.DFK_USER_ID));
                expparam.set(DeadStockInqListParams.DFK_USER_NAME, outparam.get(DeadStockInquiryDASCHParams.DFK_USER_NAME));
                expparam.set(DeadStockInqListParams.TO_RETRIEVAL_DAY, outparam.get(DeadStockInquiryDASCHParams.TO_RETRIEVAL_DAY));
                expparam.set(DeadStockInqListParams.SYS_DAY, outparam.get(DeadStockInquiryDASCHParams.SYS_DAY));
                expparam.set(DeadStockInqListParams.SYS_TIME, outparam.get(DeadStockInquiryDASCHParams.SYS_TIME));
                expparam.set(DeadStockInqListParams.RETRIEVAL_DAY, outparam.get(DeadStockInquiryDASCHParams.RETRIEVAL_DAY));
                expparam.set(DeadStockInqListParams.ITEM_CODE, outparam.get(DeadStockInquiryDASCHParams.ITEM_CODE));
                expparam.set(DeadStockInqListParams.ITEM_NAME, outparam.get(DeadStockInquiryDASCHParams.ITEM_NAME));
                expparam.set(DeadStockInqListParams.LOT_NO, outparam.get(DeadStockInquiryDASCHParams.LOT_NO));
                expparam.set(DeadStockInqListParams.AREA_NO, outparam.get(DeadStockInquiryDASCHParams.AREA_NO));
                expparam.set(DeadStockInqListParams.LOCATION_NO, outparam.get(DeadStockInquiryDASCHParams.LOCATION_NO));
                expparam.set(DeadStockInqListParams.ENTERING_QTY, outparam.get(DeadStockInquiryDASCHParams.ENTERING_QTY));
                expparam.set(DeadStockInqListParams.STOCK_CASE_QTY, outparam.get(DeadStockInquiryDASCHParams.STOCK_CASE_QTY));
                expparam.set(DeadStockInqListParams.STOCK_PIECE_QTY, outparam.get(DeadStockInquiryDASCHParams.STOCK_PIECE_QTY));
                expparam.set(DeadStockInqListParams.JAN, outparam.get(DeadStockInquiryDASCHParams.JAN));
                expparam.set(DeadStockInqListParams.ITF, outparam.get(DeadStockInquiryDASCHParams.ITF));
                if (!exporter.write(expparam))
                {
                    break;
                }
            }

            // execute print.
            try
            {
                exporter.print();
                message.setMsgResourceKey("6001010");
            }
            catch (Exception ex)
            {
                ex.printStackTrace();
                message.setMsgResourceKey("6007034");
                return;
            }

            // write part11 log.
            P11LogWriter part11Writer = new P11LogWriter(conn);
            Part11List part11List = new Part11List();
            part11List.add(txt_LastRetrievalDate.getStringValue(), "");
            part11Writer.createOperationLog(ui, ConvertUtil.objectToInt(EmConstants.OPELOG_CLASS_PRINT), part11List);

            // commit.
            conn.commit();
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
            message.setMsgResourceKey(ExceptionHandler.getDisplayMessage(ex, this));
        }
        finally
        {
            if (dasch != null)
            {
                dasch.close();
            }
            if (exporter != null)
            {
                exporter.close();
            }
            DBUtil.rollback(conn);
            DBUtil.close(conn);
        }
    }

    /**
     *
     * @throws Exception
     */
    private void btn_Xls_Click_Process()
            throws Exception
    {
        // input validation.
        txt_LastRetrievalDate.validate(this, true);

        // get locale.
        DfkUserInfo ui = (DfkUserInfo)getUserInfo();
        Locale locale = httpRequest.getLocale();

        Connection conn = null;
        DeadStockInquiryDASCH dasch = null;
        Exporter exporter = null;
        try
        {
            // open connection.
            conn = ConnectionManager.getRequestConnection(this);
            dasch = new DeadStockInquiryDASCH(conn, this.getClass(), locale, ui);
            dasch.setForwardOnly(true);

            // set input parameters.
            DeadStockInquiryDASCHParams inparam = new DeadStockInquiryDASCHParams();
            inparam.set(DeadStockInquiryDASCHParams.LAST_RETRIEVAL_DATE, txt_LastRetrievalDate.getValue());

            // check count.
            int count = dasch.count(inparam);
            if (count == 0)
            {
                message.setMsgResourceKey("6003011");
                return;
            }

            // DASCH call.
            dasch.search(inparam);

            // open exporter.
            ExporterFactory factory = new WmsExporterFactory(locale, ui);
            exporter = factory.newExcelExporter("DeadStockInqList", getSession());
            File downloadFile = exporter.open();

            // export.
            while (dasch.next())
            {
                Params outparam = dasch.get();
                DeadStockInqListParams expparam = new DeadStockInqListParams();
                expparam.set(DeadStockInqListParams.RETRIEVAL_DAY, outparam.get(DeadStockInquiryDASCHParams.RETRIEVAL_DAY));
                expparam.set(DeadStockInqListParams.ITEM_CODE, outparam.get(DeadStockInquiryDASCHParams.ITEM_CODE));
                expparam.set(DeadStockInqListParams.ITEM_NAME, outparam.get(DeadStockInquiryDASCHParams.ITEM_NAME));
                expparam.set(DeadStockInqListParams.LOT_NO, outparam.get(DeadStockInquiryDASCHParams.LOT_NO));
                expparam.set(DeadStockInqListParams.AREA_NO, outparam.get(DeadStockInquiryDASCHParams.AREA_NO));
                expparam.set(DeadStockInqListParams.LOCATION_NO, outparam.get(DeadStockInquiryDASCHParams.LOCATION_NO));
                expparam.set(DeadStockInqListParams.ENTERING_QTY, outparam.get(DeadStockInquiryDASCHParams.ENTERING_QTY));
                expparam.set(DeadStockInqListParams.STOCK_CASE_QTY, outparam.get(DeadStockInquiryDASCHParams.STOCK_CASE_QTY));
                expparam.set(DeadStockInqListParams.STOCK_PIECE_QTY, outparam.get(DeadStockInquiryDASCHParams.STOCK_PIECE_QTY));
                expparam.set(DeadStockInqListParams.JAN, outparam.get(DeadStockInquiryDASCHParams.JAN));
                expparam.set(DeadStockInqListParams.ITF, outparam.get(DeadStockInquiryDASCHParams.ITF));
                if (!exporter.write(expparam))
                {
                    message.setMsgResourceKey("6001031\t"
                            + Formatter.getNumFormat(count)
                            + "\t"
                            + Formatter.getNumFormat(CommonParam.getIntParam("MAX_NUMBER_OF_XLS")
                    - exporter.getHeaderRowsCount()));
                    break;
                }
            }

            // write part11 log.
            P11LogWriter part11Writer = new P11LogWriter(conn);
            Part11List part11List = new Part11List();
            part11List.add(txt_LastRetrievalDate.getStringValue(), "");
            part11Writer.createOperationLog(ui, ConvertUtil.objectToInt(EmConstants.OPELOG_CLASS_XLS), part11List);

            // commit.
            conn.commit();

            // redirect.
            download(downloadFile.getPath());
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
            message.setMsgResourceKey(ExceptionHandler.getDisplayMessage(ex, this));
        }
        finally
        {
            if (dasch != null)
            {
                dasch.close();
            }
            if (exporter != null)
            {
                exporter.close();
            }
            DBUtil.rollback(conn);
            DBUtil.close(conn);
        }
    }

    /**
     *
     * @throws Exception
     */
    private void btn_Clear_Click_Process()
            throws Exception
    {
        // clear.
        txt_LastRetrievalDate.setValue(null);
    }

    /**
     * Displays Screen title.
     *
     * @throws Exception
     */
    private void setTitle()
            throws Exception
    {
        // get Menu parameters from httpRequest
        String menuparam = this.getHttpRequest().getParameter(Constants.MENUPARAM);
        if (menuparam != null)
        {
            String title = CollectionUtils.getMenuParam(0, menuparam);
            String functionID = CollectionUtils.getMenuParam(1, menuparam);
            String menuID = CollectionUtils.getMenuParam(2, menuparam);

            // update Title information to view state to display when screen is refreshed
            viewState.setString(Constants.M_TITLE_KEY, title);
            viewState.setString(Constants.M_FUNCTIONID_KEY, functionID);
            viewState.setString(Constants.M_MENUID_KEY, menuID);

            lbl_SettingName.setResourceKey(title);
        }
        else if (this.getTitleResourceKey() != null && !this.getTitleResourceKey().equals(""))
        {
            // If there is no title , get the title key from ResourceKey (page.xml)
            // this is used for POPUP tilte keys
            lbl_SettingName.setResourceKey(this.getTitleResourceKey());
        }
        else if (viewState.getString(Constants.M_TITLE_KEY) != null)
        {
            // Set screen title
            lbl_SettingName.setResourceKey(viewState.getString(Constants.M_TITLE_KEY));
        }
    }

    //------------------------------------------------------------
    // utility methods
    //------------------------------------------------------------
    /**
     * Returns current repository info for this class
     *
     * @return version
     */
    public static String getVersion()
    {
        return "$Id$";
    }
}
//end of class
