/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_co_daifuku_wms_base_util_sessionmanage_SessionManage */

#ifndef _Included_jp_co_daifuku_wms_base_util_sessionmanage_SessionManage
#define _Included_jp_co_daifuku_wms_base_util_sessionmanage_SessionManage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_co_daifuku_wms_base_util_sessionmanage_SessionManage
 * Method:    getSessionList
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jp_co_daifuku_wms_base_util_sessionmanage_SessionManage_getSessionList
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jp_co_daifuku_wms_base_util_sessionmanage_SessionManage
 * Method:    sendMessage
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_daifuku_wms_base_util_sessionmanage_SessionManage_sendMessage
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     jp_co_daifuku_wms_base_util_sessionmanage_SessionManage
 * Method:    logoff
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_daifuku_wms_base_util_sessionmanage_SessionManage_logoff
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     jp_co_daifuku_wms_base_util_sessionmanage_SessionManage
 * Method:    disconnect
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_daifuku_wms_base_util_sessionmanage_SessionManage_disconnect
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     jp_co_daifuku_wms_base_util_sessionmanage_SessionManage
 * Method:    shutdownSystem
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_daifuku_wms_base_util_sessionmanage_SessionManage_shutdownSystem
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
